apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-auth-flapi-deployment
  namespace: dev-auth-flapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-auth-flapi
  template:
    metadata:
      labels:
        app: dev-auth-flapi
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            /opt/keycloak/bin/kc.sh build &&
            /opt/keycloak/bin/kc.sh start --optimized \
            --kc-proxy=edge \
            --db=mariadb \
            --db-url=jdbc:mariadb://109.234.165.225:3306/reco5282_auth_flapi_development-remote \
            --db-username=$(KC_DB_USERNAME) \
            --db-password=$(KC_DB_PASSWORD) \
            --hostname=dev.auth.flapi.org
        env:
        - name: KC_PROXY
          value: "edge"
        - name: KC_DB
          value: "mariadb"
        - name: KC_DB_URL
          value: "jdbc:mariadb://109.234.165.225:3306/reco5282_auth_flapi_development-remote"
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: dev-auth-flapi-db-secret
              key: DB_USER
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-auth-flapi-db-secret
              key: DB_PASSWORD
        - name: KC_HOSTNAME
          value: "dev.auth.flapi.org"
        - name: KC_HTTPS_CERTIFICATE_FILE
          value: "/etc/x509/https/tls.crt"
        - name: KC_HTTPS_CERTIFICATE_KEY_FILE
          value: "/etc/x509/https/tls.key"
        - name: KC_HTTP_ENABLED
          value: "false"
        volumeMounts:
          - name: keycloak-tls
            mountPath: "/etc/x509/https"
            readOnly: true
        ports:
        - containerPort: 8080
      volumes:
      - name: keycloak-tls
        secret:
          secretName: dev-auth-flapi-tls
