apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-auth-flapi-deployment
  namespace: dev-auth-flapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-auth-flapi
  template:
    metadata:
      labels:
        app: dev-auth-flapi
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            /opt/keycloak/bin/kc.sh build &&
            /opt/keycloak/bin/kc.sh start --optimized \
            --db-url=jdbc:mariadb://109.234.165.225:3306/reco5282_auth_flapi_development-remote \
            --db-username=$(KC_DB_USERNAME) \
            --db-password=$(KC_DB_PASSWORD) \
            --hostname=dev.auth.flapi.org
        env:
        - name: KC_PROXY
          value: "edge"
        - name: KC_DB
          value: "mariadb"
        - name: KC_DB_URL
          value: "jdbc:mariadb://109.234.165.225:3306/reco5282_auth_flapi_development-remote"
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: dev-auth-flapi-db-secret
              key: DB_USER
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-auth-flapi-db-secret
              key: DB_PASSWORD
        - name: KC_HOSTNAME
          value: "dev.auth.flapi.org"
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "SuperSecurePassword"
        - name: KC_HOSTNAME_ADMIN_URL
          value: "https://dev.auth.flapi.org"
        - name: KC_HTTP_ENABLED
          value: "true"
        ports:
        - containerPort: 8080