apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-auth-flapi-cert
  namespace: staging-auth-flapi
spec:
  secretName: staging-auth-flapi-tls
  dnsNames:
    - staging.auth.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
