parent=keycloak
styles=css/flapi.css
scripts=js/fontawesome-kit.js js/submit-login.js

kcHtmlClass=flapi__login--html
kcLoginClass=flapi__login--container
kcFormCardClass=flapi__login--form-card
kcButtonClass=flapi__login--button
kcInputClass=flapi__login--input
kcLabelClass=flapi__login--label
kcInputGroup=flapi__login--input-group
## Password visibility
kcFormPasswordVisibilityButtonClass=flapi__login--password-visibility
kcFormPasswordVisibilityIconShow=far fa-eye
kcFormPasswordVisibilityIconHide=far fa-eye-slash
kcFormSettingClass=flapi__login--form-setting